name: httpd setup
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    vars.yml
  tasks:
    - name: port변경
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: '^Listen\s+'
        line: Listen {{ webport }}
      notify:
        - httpd restart

  handlers:
    - name: httpd restart
      service:
        name: httpd
        state: restarted
